name: Release test

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"

      - name: build apk
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.x
      - run: flutter pub get
      # - run: flutter build apk
      # - run: flutter build appbundle
      - run: flutter build ios --release --no-codesign
      - run: cd ios
      - run: xcodebuild archive -workspace Runner.xcworkspace -scheme Runner -archivePath build/Runner.xcarchive
      - run: xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportPath build/ -exportOptionsPlist exportOptions.plist




      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   id: release_id
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with: 
      #     token: ${{ secrets.RELEASE_TOKEN }}
      #     files: |
      #       build/ios/iphoneos/*
          
      # build/app/outputs/flutter-apk/app-release.apk
      # build/app/outputs/bundle/release/app-release.aab