name: Release test

on:
  push:
    tags:
      - '*'

jobs:
  BuildAPKAndRelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"

      - name: build apk
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.x
      - run: flutter pub get
      - run: flutter build apk
      # - run: flutter build appbundle
      # - run: flutter build ipa --release --no-codesign

      # - run: mkdir build/ios/archive/Runner.xcarchive/Products/Applications/Payload/
      # - run: cp -R build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app build/ios/archive/Runner.xcarchive/Products/Applications/Payload/
      # - run: zip -r build/app.ipa build/ios/archive/Runner.xcarchive/Products/Applications/Payload/

      - run: cp -R build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/myOwnName.apk
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: release_id
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            build/app/outputs/flutter-apk/myOwnName.apk
          
      # build/app.ipa
      # build/app/outputs/bundle/release/app-release.aab