name: Release test

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"

      - name: build apk
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.x
      - run: flutter pub get
      # - run: flutter build apk
      # - run: flutter build appbundle
      - run: flutter build ipa --release --no-codesign
      - run: cd build/ios/archive/Runner.xcarchive/Products/Applications
      - run: cat Runner.app/Info.plist
      - run: mkdir Payload
      - run: cp -R Runner.app Payload/
      - run: zip -r Runner.ipa Payload
      - run: ls -l Runner.ipa



      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   id: release_id
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with: 
      #     token: ${{ secrets.RELEASE_TOKEN }}
      #     files: |
      #       build/Runner.ipa
          
      # build/app/outputs/flutter-apk/app-release.apk
      # build/app/outputs/bundle/release/app-release.aab